version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: ufc_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ufc_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: